export enum CookieErrorReason {
  EmptySecrets = 'empty_secrets',
  InvalidSecret = 'invalid_secret',
  InvalidSignature = 'invalid_signature',
  SignatureVerificationFailed = 'signature_verification_failed',
  InvalidEncryptionSecret = 'invalid_encryption_secret',
  InvalidCiphertext = 'invalid_ciphertext',
  DecryptionFailed = 'decryption_failed',
  SecurePrefixRequiresSecure = 'secure_prefix_requires_secure',
  HostPrefixRequiresSecure = 'host_prefix_requires_secure',
  HostPrefixForbidsDomain = 'host_prefix_forbids_domain',
  HostPrefixRequiresRootPath = 'host_prefix_requires_root_path',
  SigningNotConfigured = 'signing_not_configured',
  EncryptionNotConfigured = 'encryption_not_configured',
  InvalidAlgorithm = 'invalid_algorithm',
  InvalidCookieName = 'invalid_cookie_name',
  CookieTooLarge = 'cookie_too_large',
  SameSiteNoneRequiresSecure = 'samesite_none_requires_secure',
  MaxLifetimeExceeded = 'max_lifetime_exceeded',
}
